* mizrahi-tefahot.co.il .xls exporter to .qif
If you happen to be a customer of this bank, and you'd like to export, save and manipulate your financial data using something like Quicken or GnuCash - this package is for you.
This has been tested and found to work with Mizrahi exported files from June 2015, and imported with GnuCash 2.6.1
* Installation
run "npm install". this is expected to setup dependencies (coffee-script, qif, cheerio).
* Usage
1. login to mizrahi-tefahot.co.il and export the data you'd like to work with in .xls format.
2. pipe the exported file(s) into the conversion utility. Be sure to specify either "checking" or "credit" as an argument to the importer, depending on the file type. Pipe the output to your destination file
3. import the .qif file in GnuCash or whatever it is that you use.
* Example
#+BEGIN_EXAMPLE
cat ~/path/to/AccountActivity.xls | coffee mizrachi-parse.coffee checking > AccountActivity.qif
#+END_EXAMPLE
* Issues / TODO
- [ ] mizrahi's checking mode export date is ambiguous. As a result, GnuCash will prompt what format the file could be used for.
- [ ] when importing exports with overlapping date ranges, the burden of deduplication falls upon GnuCash. we could make it easier by allowing to provide date range arguments for the QIF exported data.
  


